### ISSUE TITLE
Pytest not providing expect fixture

### ISSUE THREAD

**Issue by DavidAntliff** [okken/pytest-expect#2]
pytest-expect-1.1.0 is not working for me with python 3.5.5 and pytest-4.0.2. I have used it successfully with older versions of python and pytest, just not recently.

`pytest --fixtures` does not show `expect` as a valid fixture name. Tests that try to invoke the `expect` fixture fail with `fixture 'expect' not found`. 

I have tried coaxing pytest to include the plugin with `pytest_plugins = ["plugins.pytest_expect.plugin"]
` in `conftest.py` however that doesn't seem to help.

Is this plugin expected to work with these versions of python and pytest?

**Comment by DavidAntliff** [comment]
`pytest -sv --trace-config` shows some suspicious info:

```
========================================================= test session starts =========================================================
platform linux -- Python 3.5.5, pytest-4.0.2, py-1.7.0, pluggy-0.8.0 -- /home/work/venv/bin/python3
using: pytest-4.0.2 pylib-1.7.0
setuptools registered plugins:
  pytest-repeat-0.7.0 at /home/work/venv/lib/python3.5/site-packages/pytest_repeat.py
  pytest-expect-1.1.0 at /home/work/venv/lib/python3.5/site-packages/pytest_expect/expect.py
active plugins:
    ....
    281473681242544     : <pytest_expect.expect.ExpectationPlugin object at 0xffffb2c8b9b0>
    pytest_expect       : /home/work/venv/lib/python3.5/site-packages/pytest_expect/expect.py
cachedir: .pytest_cache
rootdir: /home/work/venv/src/sptest-platform, inifile:
plugins: repeat-0.7.0, expect-1.1.0
```

What's with the plugin called `281473681242544`? Is that expected?

**Comment by okken** [comment]
David, Apologies that it isn't working right for you.
Development has moved to [pytest-check](https://github.com/okken/pytest-check)
